### ISSUE TITLE
amazing

### ISSUE THREAD

**Issue by Adrihun** [DragonetMC/Dragonet#17]
Thank you soo much.

I am a PC server developer, and I am using Bungeecord 1.12 (latest), with Spigot 1.8.9 as lobby, is there a way to install dragonnet into my server so PE & PC players can play?

I don't know how to set it up so it would be really nice if you could help

thank you

**Comment by Pet0203** [comment]
Hi!

I’m going to answer this fast and simple, because I don’t have time atm.

1. This project is not maintained by the looks...
2. It’s not even close to being finished.
3. Dragonet is a standalone server software, like spigot, it’s not a plugin nor a proxy. DragonProxy allows PE players to join PC servers and so on, but that project too, is no longer maintained.

**Comment by DaMatrix** [comment]
tbh dragonetmc has been dead for like 2 years now
